### ISSUE TITLE
unikube.yaml context is not considered

### ISSUE THREAD

**Issue by buschNT** [unikubehq/cli#161]
Looks like the `os.path.dirname` command for the class "UnikubeFile_1_0" does not provide the right path. `unikube orga info` should for example provide the information of the "test" organization if it is executed in the console with the following unikube.yaml:

```yaml
context:
  organization: test
  project: test
  deck: test

apps:
  projects:
    build:
      context: .
      dockerfile: Dockerfile
.......
```
