### ISSUE TITLE
Structure of `unikube.yaml` and `app switch` insufficient

### ISSUE THREAD

**Issue by schwobaseggl** [unikubehq/cli#239]
```yaml
apps:
  projects:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    deployment: mumpiz-web
    command: python manage.py serve --command "collectstatic --no-input" --port {port} --autoreload --static
    volumes:
      - ./src:/app
    env:
      - DJANGO_DEBUG: "True"
```

`projects` could be really anything at this point, it wouldn't make any difference as we are only ever accessing the first key under `apps`.

The problem I currently have is the following: I would like to switch two deployments that have the same codebase (aka use the same unikube.yaml): the web application and the celery worker. While I can supply the `--deployment` flag to the `app switch` command:

```bash
unikube app switch --deployment mumpiz-worker
```
the command is still taken from the unikube file. This clearly makes no sense whatsoever which is ok as this was always meant to be expanded. I suggest the following: Given the unikube file:

```yaml
apps:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    deployment: mumpiz-web
    command: python manage.py serve --command "collectstatic --no-input" --port {port} --autoreload --static
    volumes:
      - ./src:/app
    env:
      - DJANGO_DEBUG: "True"
  worker:
    build: # same as above
    deployment: mumpiz-worker
    command: "celery -A configuration.celery.app worker -O fair"
    volumes:  # same
    env:  # same
```

One should be able to specify the `app`
```bash
unikube app switch --app worker
```
and then take all the information from the respective key under `apps`. 

**Problem:**

What happens if no app is specified in the switch command? 

I suggest to take the first app under `apps` as we do now implicitly. Since we only support Python >= 3.7 (where dicts preserve insertion order), the key order in the resulting `dict` must correspond to the order in which the apps are specified in the `unikube.yaml`.
