### ISSUE TITLE
`unikube.yaml` to support image tag

### ISSUE THREAD

**Issue by Schille** [unikubehq/cli#272]
Currently it is not possible to address an arbitrary image to be run during a switch operation, but only one build locally. In order to speed up the process of the switch operation the `unikube.yaml` should support an `image` attribute.

Currently it its:
```yaml
apps:
  [...]
    build:
      context: <Path to Docker build root>
      dockerfile: <Path to Dockerfile>
      target: <Dockerfile build target>
```
In the future the Unikube CLI should support:
```yaml
apps:
  [...]
    image: my-service-image:latest
```
Since development images are usually already built somewhere this could be a good alternative. Instead of building the docker image on the local machine, this would pull an image from somewhere and make this the basis for the switch operation.
